---
global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'dragonfly'
    scrape_interval: 2s

    static_configs:
      - targets: ['dragonfly:6379']
        labels:
          agent_hostname: 'dragonfly'

  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]

  - job_name: 'talvi-backend'
    static_configs:
      - targets: [ 'backend:8081' ]